void Error_CannotRunScript(string strFunName,Connector pConnector)
{
	print("指令错误或是没有权限"+strFunName);
	if (strFunName == "SetRemoteFun")
	{
		//说明mainserver还未设置权限，再申请一次
		pConnector->RunScript(0,"SetRemoteFun","CalFun1");
	}
}
void main()
{
	Connector pConnector = NewConnector("127.0.0.1",10000, "inner","123456");
	pConnector->SetScriptLimit("Error_CannotRunScript",1);
	pConnector->SetScriptLimit("CalFun1",1);
	wait(100);
	print("申请辅助CalFun1函数");
	pConnector->RunScript(0,"SetRemoteFun","CalFun1");
}