void InitConnector(Connector pConnector)
{
	pConnector->SetHeadProtocol("inner","server","123456");
	Connector pServerConnector = GetVal4Data("Data","ServerConnector");
	pConnector->SetRoute(pServerConnector);
}

void main()
{
	//初始化数据
	InitData("Data");

	SetListenPort(9998,"InitConnector");

	Connector pClient = NewConnector("127.0.0.1",9999);
	pClient ->SetHeadProtocol("inner","client","123456");
	SetVal2Data("Data","ServerConnector",pClient);
	print("启动完成");
}