void InitConnector(Connector pConnector)
{
	//网关链接后，设置路由链接的初始函数
	pConnector->SetRouteInitScript("InitRouteConnector");

}
void InitRouteConnector(Connector pConnector)
{
	//一个客户端通过网关路由链接过来
	pConnector->SetScriptLimit("Error_CannotRunScript",1);
	pConnector->SetScriptLimit("RegisterAccount",1);
	pConnector->SetScriptLimit("LoginAccount",1);
	print("route connect");
}
void RegisterAccount(string strAccount, string password, Connector pConnector)
{
	CArray AccountArray = GetVal4Data("Data","Account");
	if (CheckClassPoint(AccountArray) == 0)
	{
		AccountArray = NewArray();
		SetVal2Data("Data","Account",AccountArray);
	}
	CAccount pAccount = AccountArray->GetVal(strAccount);
	if (CheckClassPoint(pAccount))
	{
		//账号已存在，注册失败
		pConnector->RunScript(0,"RegisterFail",pAccount);
		return;
	}
	pAccount = new CAccount;
	pAccount->SetAccountName(strAccount);
	pAccount->SetPassword(password);
	pAccount->SetNickName(strAccount);

	pAccount->SetConnect(pConnector);
	pConnector->SetAccount(strAccount);
	AccountArray->SetVal(strAccount,pAccount);
	//发送注册成功，登录成功
	pConnector->RunScript(0,"LoginSuccess",pAccount);
	pConnector->SetScriptLimit("Talk",1);
}
void LoginAccount(string strAccount, string password, Connector pConnector)
{
	CArray AccountArray = GetVal4Data("Data","Account");
	if (0 == CheckClassPoint(AccountArray))
	{
		AccountArray = NewArray();
		SetVal2Data("Data","Account",AccountArray);
	}
	CAccount pAccount = AccountArray->GetVal(strAccount);
	if (0 == CheckClassPoint(pAccount))
	{
		//账号不存在，登录失败
		pConnector->RunScript(0,"LoginFail",pAccount,1);
		return;
	}
	if (password != pAccount->GetPassword())
	{
		//密码错误，登录失败
		pConnector->RunScript(0,"LoginFail",pAccount,2);
		return;
	}

	pAccount->SetConnect(pConnector);
	pConnector->SetAccount(strAccount);
	pConnector->RunScript(0,"LoginSuccess",pAccount);
	pConnector->SetScriptLimit("Talk",1);
}

void Talk(string strContent, Connector pConnector)
{

	if (strContent != "")
	{
		CArray AccountArray = GetVal4Data("Data","Account");
		if (CheckClassPoint(AccountArray))
		{
			CAccount pMainAccount = AccountArray->GetVal(pConnector->GetAccount());
			int i = 0;
			while (i < AccountArray->GetSize())
			{
				CAccount pAccount = AccountArray->GetValByIndex(i);
				if (CheckClassPoint(pAccount))
				{
					Connector pAccClient = pAccount->GetConnect();
					if (CheckClassPoint(pAccClient))
					{
						pAccClient->RunScript(0,"SendMessage",pMainAccount,strContent);
					}
				}
				i = i + 1;
			}
		}
	}
}
void main()
{
	//初始化数据
	CData pData = GetData("Data");
	//设置网关连来的端口
	SetListenPort(9999,"InitConnector");

	print("启动完成");
}