void InitConnector(Connector pConnector)
{
	pConnector->SetScriptLimit("Error_CannotRunScript",1);
	pConnector->SetScriptLimit("RegisterAccount",1);
	pConnector->SetScriptLimit("LoginAccount",1);
}
void RegisterAccount(string strAccount, string password, Connector pConnector)
{
	CArray AccountArray = GetVal4Data("Data","Account");
	if (CheckClassPoint(AccountArray) == 0)
	{
		AccountArray = NewArray();
		SetVal2Data("Data","Account",AccountArray);
	}
	CAccount pAccount = AccountArray->GetVal(strAccount);
	if (CheckClassPoint(pAccount))
	{
		//账号已存在，注册失败
		pConnector->RunScript(0,"RegisterFail",pAccount);
		return;
	}
	pAccount = new CAccount;
	pAccount->SetAccountName(strAccount);
	pAccount->SetPassword(password);
	pAccount->SetNickName(strAccount);

	pAccount->SetConnectID(pConnector->GetID());
	pConnector->SetAccount(strAccount);
	AccountArray->SetVal(strAccount,pAccount);
	//发送注册成功，登录成功
	pConnector->RunScript(0,"LoginSuccess",pAccount);
	pConnector->SetScriptLimit("Talk",1);
}
void LoginAccount(string strAccount, string password, Connector pConnector)
{
	CArray AccountArray = GetVal4Data("Data","Account");
	if (0 == CheckClassPoint(AccountArray))
	{
		AccountArray = NewArray();
		SetVal2Data("Data","Account",AccountArray);
	}
	CAccount pAccount = AccountArray->GetVal(strAccount);
	if (0 == CheckClassPoint(pAccount))
	{
		//账号不存在，登录失败
		pConnector->RunScript(0,"LoginFail",pAccount,1);
		return;
	}
	if (password != pAccount->GetPassword())
	{
		//密码错误，登录失败
		pConnector->RunScript(0,"LoginFail",pAccount,2);
		return;
	}

	pAccount->SetConnectID(pConnector->GetID());
	pConnector->SetAccount(strAccount);
	pConnector->RunScript(0,"LoginSuccess",pAccount);
	pConnector->SetScriptLimit("Talk",1);
}

void Talk(string strContent, Connector pConnector)
{

	if (strContent != "")
	{
		CArray AccountArray = GetVal4Data("Data","Account");
		if (CheckClassPoint(AccountArray))
		{
			CAccount pMainAccount = AccountArray->GetVal(pConnector->GetAccount());
			int i = 0;
			while (i < AccountArray->GetSize())
			{
				CAccount pAccount = AccountArray->GetValByIndex(i);
				if (CheckClassPoint(pAccount))
				{
					Connector pAccClient = GetConnector(pAccount->GetConnectID());
					if (CheckClassPoint(pAccClient))
					{
						pAccClient->RunScript(0,"SendMessage",pMainAccount,strContent);
					}
				}
				i = i + 1;
			}
		}
	}
}
void main()
{
	//初始化数据
	CData pData = GetData("Data");

	SetListenPort(9999);
	print("启动完成");
}