void InitConnector(Connector pConnector)
{
	pConnector->SetHeadProtocol("inner","server","123456");
}
void InitAssistConnector(Connector pConnector)
{
	pConnector->SetHeadProtocol("inner","server","123456");
	print("辅助服务器连接");
	pConnector->SetScriptLimit("SetRemoteFun",1);
}
void SetRemoteFun(string FunName, Connector pConnector)
{
	pConnector->SetRemoteFunction(FunName);
}

void main()
{
	//初始化数据
	CData pData = GetData("Data");

	//9999给客户端用
	SetListenPort(9999,"InitConnector");
	//10000端口给辅助服务器用
	SetListenPort(10000,"InitAssistConnector");
	print("启动完成");

	while(1)
	{
		CalFun2(100);
		print("===================");
		wait(1000);
	}
}